---
title: "Technion AI Program"
subtitle: "Online Info Session"
author: "Royi Avital"
editor:
  render-on-save: false
execute:
  freeze: true
format: 
  revealjs:
    width: 1200
    height: 800
    footer: "[Technion - The School of Continuing Education](https://cont-edu.technion.ac.il)"
    logo: "https://i.imgur.com/8Eg8S2J.png"
    toc: true
    toc-title: Agenda
    toc-depth: 2
    margin: 0.05
    navigation-mode: vertical
revealjs-plugins:
  - attribution
filters:
  - roughnotation
---

# Building The AI Program

## Building the AI Program

:::{.incremental}
 * {{< iconify pajamas issue-type-objective >}} Setting the _objective_ - Capable _real world_ AI developers / practitioners.
 * {{< iconify fluent people-audience-20-filled >}} Defining the target _audience_.  
 * {{< iconify game-icons team-idea >}} Building the tutoring _team_.
 * {{< iconify clarity list-solid >}} Building the _syllabus_.
:::

. . . 

:::{.callout-tip title="The Initiative"}

The AI Program was initiative by the industry, asking for a program to counter the shortage in highly capable AI developers / practitioners.

:::

## Royi Avital

 - MSc in EE from the Technion.
 - Owner of [_Fixel Algorithms_](https://fixelalgorithms.gitlab.io)  
   Consulting, Outsourcing and Training for Algorithms.
 - Algorithm group leader for many years in the defense industry.
 - Specializations: Signal and Image Processing, Computer Vision, Optimization, Estimation, Machine Learning, Deep Learning, ...
 - CTO on 3 Start Up's.
 - Teaching: Technion, Rafael, IAI, Samsung, etc...
 - Contact: `royia@technion.ac.il`.

# The Program

## Syllabus {auto-animate=true}

:::{.incremental style="font-size: 70%;"}
 * Essentials
   * Linear Algebra & Optimization.
   * Probability & Estimation.
   * _Scientific_ Python.
   * Development Environment.
 * Classic Machine Learning
   * Overview and Concepts.
   * Supervised
     * Classification.
     * Regression.
   * Unsupervised
     * Clustering.
     * Dimensionality Reduction.
     * Anomaly Detection.
:::

## Syllabus {.unlisted auto-animate=true}

:::{.incremental style="font-size: 70%;"}
 * Deep Learning - Neural Networks
   * Motivation & Concept.
   * Deep Learning Framework.
   * Feed Forward Networks.
   * Training & Regularization.
 * Deep Learning for Computer Vision
   * Convolutional Neural Networks (CNN).
   * Signal Classification.
   * Architectures.
   * Training Phase & Augmentation.
   * Transfer Learning & Active Learning.
   * Image Classification.
   * Object Detection.
:::

## Workshops

:::{.incremental}
 * Working with Cloud based Virtual Machine.
 * Object Detection with YOLO Models.
 * Image Segmentation with U-Net Models.
 * Processing Text / Image Data.
 * Object Tracking with Large Vision Models (Optional).
 * Contrastive Learning for Object Recognition (Optional).
:::

## Projects

 - There are 2 projects:
   - Classic Machine Learning.
   - Deep Learning (Computer Vision / LLM).
 - The projects should be about _real world problem_.
 - The projects should imitate, in a _small time scale_, a project in the industry.
 - During the time dedicated for projects the tutors will be available for guidance.
 - The task can be either initiative of the team or proposed by the tutors.
 - Projects in doubles / triplets.

. . . 

:::{.callout-note title="The Objective"}

Gaining experience in solving _real world_ problems using AI.

:::

## The Learning Experience

 - _Self Contained_ slides.
 - Hands on Code in _Jupyter Notebooks_.  
   Over 100 Code Notebooks!
 - Exercises (Self / Class) based on _Jupyter Notebooks_.
 - Learning Session / Exercise Session.
 - Technion backed: 
   - Student Email.
   - Moodle Course Site.
   - 200 Hours Cloud VM for DL.

## Prerequisites

:::{.incremental}
 * {{< iconify ic twotone-science >}} Some _science_ or a like background.
 * {{< iconify solar programming-bold >}} Some knowledge in _programming_ (Python is recommended).  
 * {{< iconify arcticons math-wiki >}} No fear of _Math_.
 * {{< iconify fluent-mdl2 work-flow >}} Willing to work _hard_.
 * {{< iconify fluent quiz-new-20-filled >}} Above 60 in the [entrance quiz](https://hackmd.io/@Fixel/HyJT6urya).
:::

. . . 

:::{.callout-note title="Expectations"}

The motivation behind the quiz is about aligning expectations.

:::

# Why the Technion AI Program?

## The Background Mini Courses

:::{.incremental}
 * {{< iconify arcticons deepstash >}} We want to go deeper in the understanding level.
 * {{< iconify arcticons algorithms >}} We want to understand the algorithms.  
 * {{< iconify clarity language-solid >}} We need a language for that: Programming & Mathematics.
 * {{< iconify carbon scis-transparent-supply >}} No shortcuts, we'll supply it.
 * {{< iconify arcticons best-connect >}} It will make the class homogenous in its capabilities.
:::

. . .

:::{.callout-note title="Intuition"}

The deeper understanding is the source of intuition and problem solving capabilities.

:::

## What Is Different?

:::{.incremental}
 * {{< iconify ph student-fill >}} The students.
 * {{< iconify game-icons flag-objective >}} The objective.  
 * {{< iconify codicon symbol-method >}} The method.
 * {{< iconify ic sharp-scale >}} The scale.
:::

. . .


:::{.callout-important title="Why?"}

 - We start high.
 - We aim higher.

:::



